/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiVocabImageRouteImport } from './routes/api/vocab-image'
import { Route as ApiTestKeyRouteImport } from './routes/api/test-key'
import { Route as ApiMcpHealthRouteImport } from './routes/api/mcp-health'
import { Route as ApiLessonRouteImport } from './routes/api/lesson'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as ApiOauthTokenRouteImport } from './routes/api/oauth/token'
import { Route as ApiOauthRegisterRouteImport } from './routes/api/oauth/register'
import { Route as ApiOauthAuthorizeRouteImport } from './routes/api/oauth/authorize'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocabImageRoute = ApiVocabImageRouteImport.update({
  id: '/api/vocab-image',
  path: '/api/vocab-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestKeyRoute = ApiTestKeyRouteImport.update({
  id: '/api/test-key',
  path: '/api/test-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpHealthRoute = ApiMcpHealthRouteImport.update({
  id: '/api/mcp-health',
  path: '/api/mcp-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonRoute = ApiLessonRouteImport.update({
  id: '/api/lesson',
  path: '/api/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthTokenRoute = ApiOauthTokenRouteImport.update({
  id: '/api/oauth/token',
  path: '/api/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthRegisterRoute = ApiOauthRegisterRouteImport.update({
  id: '/api/oauth/register',
  path: '/api/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthAuthorizeRoute = ApiOauthAuthorizeRouteImport.update({
  id: '/api/oauth/authorize',
  path: '/api/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/lesson': typeof ApiLessonRoute
  '/api/mcp-health': typeof ApiMcpHealthRoute
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/vocab-image': typeof ApiVocabImageRoute
  '/p/$id': typeof PIdRoute
  '/api/oauth/authorize': typeof ApiOauthAuthorizeRoute
  '/api/oauth/register': typeof ApiOauthRegisterRoute
  '/api/oauth/token': typeof ApiOauthTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/lesson': typeof ApiLessonRoute
  '/api/mcp-health': typeof ApiMcpHealthRoute
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/vocab-image': typeof ApiVocabImageRoute
  '/p/$id': typeof PIdRoute
  '/api/oauth/authorize': typeof ApiOauthAuthorizeRoute
  '/api/oauth/register': typeof ApiOauthRegisterRoute
  '/api/oauth/token': typeof ApiOauthTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/lesson': typeof ApiLessonRoute
  '/api/mcp-health': typeof ApiMcpHealthRoute
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/vocab-image': typeof ApiVocabImageRoute
  '/p/$id': typeof PIdRoute
  '/api/oauth/authorize': typeof ApiOauthAuthorizeRoute
  '/api/oauth/register': typeof ApiOauthRegisterRoute
  '/api/oauth/token': typeof ApiOauthTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/login'
    | '/mcp'
    | '/register'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/lesson'
    | '/api/mcp-health'
    | '/api/test-key'
    | '/api/vocab-image'
    | '/p/$id'
    | '/api/oauth/authorize'
    | '/api/oauth/register'
    | '/api/oauth/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/login'
    | '/mcp'
    | '/register'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/lesson'
    | '/api/mcp-health'
    | '/api/test-key'
    | '/api/vocab-image'
    | '/p/$id'
    | '/api/oauth/authorize'
    | '/api/oauth/register'
    | '/api/oauth/token'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/login'
    | '/mcp'
    | '/register'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/lesson'
    | '/api/mcp-health'
    | '/api/test-key'
    | '/api/vocab-image'
    | '/p/$id'
    | '/api/oauth/authorize'
    | '/api/oauth/register'
    | '/api/oauth/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizeRoute: typeof AuthorizeRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RegisterRoute: typeof RegisterRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiLessonRoute: typeof ApiLessonRoute
  ApiMcpHealthRoute: typeof ApiMcpHealthRoute
  ApiTestKeyRoute: typeof ApiTestKeyRoute
  ApiVocabImageRoute: typeof ApiVocabImageRoute
  PIdRoute: typeof PIdRoute
  ApiOauthAuthorizeRoute: typeof ApiOauthAuthorizeRoute
  ApiOauthRegisterRoute: typeof ApiOauthRegisterRoute
  ApiOauthTokenRoute: typeof ApiOauthTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vocab-image': {
      id: '/api/vocab-image'
      path: '/api/vocab-image'
      fullPath: '/api/vocab-image'
      preLoaderRoute: typeof ApiVocabImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-key': {
      id: '/api/test-key'
      path: '/api/test-key'
      fullPath: '/api/test-key'
      preLoaderRoute: typeof ApiTestKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-health': {
      id: '/api/mcp-health'
      path: '/api/mcp-health'
      fullPath: '/api/mcp-health'
      preLoaderRoute: typeof ApiMcpHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson': {
      id: '/api/lesson'
      path: '/api/lesson'
      fullPath: '/api/lesson'
      preLoaderRoute: typeof ApiLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/token': {
      id: '/api/oauth/token'
      path: '/api/oauth/token'
      fullPath: '/api/oauth/token'
      preLoaderRoute: typeof ApiOauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/register': {
      id: '/api/oauth/register'
      path: '/api/oauth/register'
      fullPath: '/api/oauth/register'
      preLoaderRoute: typeof ApiOauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/authorize': {
      id: '/api/oauth/authorize'
      path: '/api/oauth/authorize'
      fullPath: '/api/oauth/authorize'
      preLoaderRoute: typeof ApiOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizeRoute: AuthorizeRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RegisterRoute: RegisterRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiLessonRoute: ApiLessonRoute,
  ApiMcpHealthRoute: ApiMcpHealthRoute,
  ApiTestKeyRoute: ApiTestKeyRoute,
  ApiVocabImageRoute: ApiVocabImageRoute,
  PIdRoute: PIdRoute,
  ApiOauthAuthorizeRoute: ApiOauthAuthorizeRoute,
  ApiOauthRegisterRoute: ApiOauthRegisterRoute,
  ApiOauthTokenRoute: ApiOauthTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
